openapi: 3.0.3
info:
  title: Product Collections
  description: Products collection API allows users to search for products across a wide range of marketplaces by brand.
  version: '1.0'
  contact:
    name: Cluster Support
    email: support@datacluster.com
servers:
  - url: 'https://api.datacluster.com'
tags:
  - name: Products collection endpoints
paths:
  /v4/products:
    get:
      tags:
        - Products collection endpoints
      operationId: get-products-collection
      summary: Get products collection
      description: |-
        This is a synchronous API endpoint. This endpoint returns a product list according to the brand and marketplaces provided.
        <br/>[**Don't miss our schemas**](/docs/Making-a-request/Our-schemas.md)'
      parameters:
        - name: local
          required: false
          description: the local of the product.
          in: query
          schema:
            $ref: ../models/common/Locals.v1.yaml
            default: US
        - name: brandId
          in: query
          description: 'Cluster unique Brand Id [(see "Get Brands by brand name" endpoint)](/brands/src/main/resources/api-reference/brands-api-1.0.yaml/paths/~1v4~1brands/get).'
          required: false
          style: form
          explode: false
          schema:
            type: string
        - name: brandName
          in: query
          description: 'The name of the brand'
          required: false
          style: form
          explode: false
          schema:
            type: string
        - name: manufacturerName
          in: query
          description: 'The name of the manufacturer'
          required: false
          style: form
          explode: false
          schema:
            type: string
        - name: categories
          in: query
          description: Comma-delimited list of category ids.
          required: false
          style: form
          explode: false
          schema:
            type: string
        - name: excludeCategories
          in: query
          description: Comma-delimited list of category ids to exclude.
          required: false
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
        - name: maxItems
          description: Set a max number of items to return in the collection.
          in: query
          style: form
          explode: false
          schema:
            type: integer
        - name: contextKey
          description: A key which was returned when making the initial request for products. This key is used to retreive the following results pages.
          in: query
          explode: false
          style: form
          schema:
            type: string
          required: false
        - name: pageNumber
          description: The page number of the results to retreive. This parameter must be used in tandem with contextKey
          in: query
          explode: true
          schema:
            type: integer
          required: false
        - name: resources
          description: comma delimited resource list to include in the response.
          in: query
          explode: false
          schema:
            $ref: ../models/products-collection/ResourceType.v1.yaml
      responses:
        '200':
          description: SUCCESS.</br>**Notice - our examples were generate with mock data**
          content:
            application/json:
              schema:
                $ref: ../models/products-collection/ProductsCollectionApiResponse.v1.yaml
              examples:
                Response Example:
                  value:
                    timestamp: 1610533241
                    status: SUCCESS
                    statusMessage: Ok
                    statusCode: 200
                    requestId: efb6cfea-4921-40c3-941a-7977d84f12f7
                    result:
                      totalPages: 9
                      products:
                        - aid: AIDVM8W02001
                          parentAid: AIDVM8W02001
                          title: adidas Men's Adilette Shower Slides
                          marketPrice:
                            currencyCode: USD
                            amount: 65
                          imageUrl: 'https://m.media-amazon.com/images/I/31p8fsS9UdL._SL160_.jpg'
                          variants:
                            - aid: string
                              parentAid: string
                              title: string
                              marketPrice:
                                currencyCode: string
                                amount: 0
                              imageUrl: string
                              variants:
                                - {}
                      contextKey: efb6cfea-4921-40c3-941a-7977d84f12f7
        '400':
          $ref: '../models/common/responses/statuscode400.v1.yaml'
        '401':
          $ref: '../models/common/responses/statuscode401.v1.yaml'
        '403':
          $ref: '../models/common/responses/statuscode403.v1.yaml'
        '429':
          $ref: '../models/common/responses/statuscode429.v1.yaml'
        '500':
          $ref: '../models/common/responses/statuscode500.v1.yaml'
      security:
        - apiKey: []
        - appId: []
  /v4/products/summary:
    get:
      tags:
        - Products collection endpoints
      operationId: get-products-collection-summary
      summary: Get products collection summary
      description: |-
        This is a synchronous API endpoint. This endpoint returns summary of a product list according to the brand and marketplaces provided.
        <br/>[**Don't miss our schemas**](/docs/Making-a-request/Our-schemas.md)
      parameters:
        - name: local
          required: false
          in: query
          description: The local of the product.
          schema:
            $ref: ../models/common/Locals.v1.yaml
            default: US
        - name: brandId
          in: query
          description: 'Cluster unique Brand Id [(see "Get Brands by brand name" endpoint)](/brands/src/main/resources/api-reference/brands-api-1.0.yaml/paths/~1v4~1brands/get).'
          required: false
          style: form
          explode: false
          schema:
            type: string
        - name: brandName
          in: query
          description: The name of the brand
          required: false
          style: form
          explode: false
          schema:
            type: string
        - name: categories
          in: query
          description: List of comma delimited [amazon category ids](https://algopix.com/taxonomy/amazon_browse_node_info_US.txt) by locale.
          required: false
          style: form
          explode: false
          schema:
            type: string
        - name: excludeCategories
          in: query
          description: List of comma delimited [amazon category ids](https://algopix.com/taxonomy/amazon_browse_node_info_US.txt) by locale to exclude.
          required: false
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: SUCCESS.</br>**Notice - our examples were generate with mock data**
          content:
            application/json:
              schema:
                $ref: ../models/products-collection/ProductsSummaryResponse.v1.yaml
              examples:
                Response Example:
                  value:
                    timestamp: 1610532938
                    status: SUCCESS
                    statusMessage: Ok
                    statusCode: 200
                    requestId: 49735463-e4b6-4960-bd83-7c90043bd14a
                    result:
                      productsCount: 7090
                      brands:
                        - title: nike
                          id: 11nohTBQB_
                          precentage: 97.6
                      categories:
                        - id: '7148223411'
                          precentage: 100
                      manufacturers:
                        - title: nike
                          id: 11nohTBQB_
                          precentage: 83.3
        '400':
          $ref: '../models/common/responses/statuscode400.v1.yaml'
        '401':
          $ref: '../models/common/responses/statuscode401.v1.yaml'
        '403':
          $ref: '../models/common/responses/statuscode403.v1.yaml'
        '429':
          $ref: '../models/common/responses/statuscode429.v1.yaml'
        '500':
          $ref: '../models/common/responses/statuscode500.v1.yaml'
      security:
        - apiKey: []
        - appId: []
  /v4/products/reports:
    post:
      tags:
        - Products collection endpoints
      operationId: create-products-collection-report
      summary: Create a products report
      description: |-
        Request creating a products report. This endpoint triggers the background creation of a report. Use the ["Get report status"](../~1v4~1products~1reports~1status/get) endpoint to get the status of the report generation. use the ["Get ready report"](../~1v4~1products~1reports~1%7BreportId%7D/get) endpoint to download the report.
        <br/>[**Don't miss our schemas**](/docs/Making-a-request/Our-schemas.md)
      parameters:
        - name: local
          required: false
          in: query
          description: The local of the product.
          schema:
            $ref: ../models/common/Locals.v1.yaml
            default: US
        - name: brandId
          in: query
          description: Unique identifier for a brand.
          required: false
          style: form
          explode: false
          schema:
            type: string
        - name: brandName
          in: query
          description: brand name
          required: false
          style: form
          explode: false
          schema:
            type: string
        - name: categories
          in: query
          description: List of comma delimited [amazon category ids](https://algopix.com/taxonomy/amazon_browse_node_info_US.txt) by locale.
          required: false
          style: form
          explode: false
          schema:
            type: string
        - name: excludeCategories
          in: query
          description: List of comma delimited [amazon category ids](https://algopix.com/taxonomy/amazon_browse_node_info_US.txt) by locale to exclude.
          required: false
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
        - name: maxItems
          description: Set a max number of items to return in the collection.
          in: query
          style: form
          explode: false
          schema:
            type: integer
        - name: additionalFields
          description: Comma-delimited advanced market Fields to add to the reports. You must be authirzied for each Field.
          required: false
          in: query
          schema:
            $ref: ../models/products-collection/AdditionalFields.v1.yaml
      responses:
        '200':
          description: Ok.</br>**Notice - our examples were generate with mock data**
          content:
            application/json:
              schema:
                $ref: ../models/products-collection/ProductsCollectionCreateReportResponse.v1.yaml
              examples:
                Response Example:
                  value:
                    timestamp: 1610533241
                    status: SUCCESS
                    statusCode: 200
                    statusMessage: Ok
                    requestId: efb6cfea-4921-40c3-941a-7977d84f12f7
                    result:
                      reportId: 01f33a78-6948-47b3-8dbc-e431e1s37998
        '400':
          $ref: '../models/common/responses/statuscode400.v1.yaml'
        '401':
          $ref: '../models/common/responses/statuscode401.v1.yaml'
        '403':
          $ref: '../models/common/responses/statuscode403.v1.yaml'
        '429':
          $ref: '../models/common/responses/statuscode429.v1.yaml'
        '500':
          $ref: '../models/common/responses/statuscode500.v1.yaml'
      security:
        - apiKey: []
        - appId: []
  /v4/products/reports/status:
    get:
      tags:
        - Products collection endpoints
      operationId: get-products-report-status
      summary: Get report status
      description: Get all report status.<br>[**Don't miss our schemas**](/docs/Making-a-request/Our-schemas.md)
      parameters:
        - name: reportId
          description: Report identifier
          in: query
          style: form
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: Ok.</br>**Notice - our examples were generate with mock data**
          content:
            application/json:
              schema:
                $ref: ../models/products-collection/ProductsCollectionReportStatusResponse.v1.yaml
              examples:
                Response Example:
                  value:
                    timestamp: 1610533241
                    status: SUCCESS
                    statusCode: 200
                    statusMessage: Ok
                    requestId: efb6cfea-4921-40c3-941a-7977d84f12f7
                    result:
                      reports:
                        - id: b0cded8c-e3d5-4e57-9114-0bd09ce2d5c1
                          status: IN_PROGRESS
                          type: PRODUCTS_COLLECTION
        '400':
          $ref: '../models/common/responses/statuscode400.v1.yaml'
        '401':
          $ref: '../models/common/responses/statuscode401.v1.yaml'
        '403':
          $ref: '../models/common/responses/statuscode403.v1.yaml'
        '429':
          $ref: '../models/common/responses/statuscode429.v1.yaml'
        '500':
          $ref: '../models/common/responses/statuscode500.v1.yaml'
      security:
        - apiKey: []
        - appId: []
  '/v4/products/reports/{reportId}':
    get:
      tags:
        - Products collection endpoints
      summary: Get ready report
      description: This endpoint returns collection report file.<br>[**Don't miss our schemas**](/docs/Making-a-request/Our-schemas.md)
      operationId: get-products-collection-report
      parameters:
        - name: reportId
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Success – return zipped csv file.
        '400':
          $ref: '../models/common/responses/statuscode400.v1.yaml'
        '401':
          $ref: '../models/common/responses/statuscode401.v1.yaml'
        '403':
          $ref: '../models/common/responses/statuscode403.v1.yaml'
        '429':
          $ref: '../models/common/responses/statuscode429.v1.yaml'
        '500':
          $ref: '../models/common/responses/statuscode500.v1.yaml'
      security:
        - apiKey: []
        - appId: []
components:
  securitySchemes:
    apiKey:
      type: apiKey
      name: X-API-KEY
      in: header
      description: 'Read our [Authentication](/docs/Making-a-request/Authentication.md) article'
    appId:
      type: apiKey
      name: X-APP-ID
      in: header